(() => {
  const tg=window.Telegram?.WebApp;
  if(tg){tg.ready();tg.expand();try{tg.setHeaderColor('#041a3a');tg.setBackgroundColor('#020916')}catch(_){} }
  if(window.pdfjsLib) window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
  const PAID_TELEGRAM='CHANGE_ME';
  const MAX=10*1024*1024;
  const view=document.getElementById('view'), sheet=document.getElementById('sheet'), body=document.getElementById('sheetBody'), toastEl=document.getElementById('toast');
  const state={screen:'home',file:null,files:[],report:null,text:'',name:'',history:load('jeai_history',[]),stats:load('jeai_stats',{checks:0,docs:0,tests:0})};
  let toastTimer;
  function load(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
  function save(){localStorage.setItem('jeai_history',JSON.stringify(state.history.slice(-50)));localStorage.setItem('jeai_stats',JSON.stringify(state.stats));updateStats()}
  function updateStats(){const s=state.stats;const a=document.getElementById('statChecks');if(a)a.textContent=s.checks;const b=document.getElementById('statDocs');if(b)b.textContent=s.docs;const c=document.getElementById('statTests');if(c)c.textContent=s.tests}
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function toast(m){toastEl.textContent=m;toastEl.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toastEl.classList.remove('show'),2400)}
  function open(h){body.innerHTML=h;sheet.classList.add('open');sheet.setAttribute('aria-hidden','false')}
  function close(){sheet.classList.remove('open');sheet.setAttribute('aria-hidden','true');body.innerHTML='';state.file=null;state.files=[]}
  function paid(){if(PAID_TELEGRAM==='CHANGE_ME'){toast('Сначала укажем Telegram для платных услуг');return}const u='https://t.me/'+PAID_TELEGRAM.replace(/^@/,'');if(tg?.openTelegramLink)tg.openTelegramLink(u);else window.open(u,'_blank','noopener')}
  function addHistory(x){state.history.push({at:new Date().toISOString(),...x});save()}
  function nav(name){state.screen=name;document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));if(name==='home')renderHome();if(name==='documents')renderDocuments();if(name==='ai')openAI();if(name==='xray')openXray(state.report,state.name);if(name==='profile')renderProfile()}
  document.getElementById('brandHome').onclick=()=>nav('home');document.querySelectorAll('#nav button,[data-nav]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.nav)));document.addEventListener('click',e=>{if(e.target.closest('[data-close]'))close();const p=e.target.closest('[data-paid]');if(p){e.preventDefault();paid()}});

  function renderHome(){view.innerHTML=`<div class="hero"><div class="heroIn"><div class="pill"><i></i> РОССИЯ · ONLINE</div><h1>Юрист объясняет.<br><span>Просто. Чётко. По делу.</span></h1><p class="lead">Проверьте документ, создайте юридический текст или опишите проблему. Всё в одном месте — внутри Telegram.</p><div class="heroActions"><button class="btn btnMain" id="hAnalyze">✦ Проверить документ</button><button class="btn btnDark" id="hAI">◉ Спросить AI</button></div><div class="micro"><span>⌾ файл обрабатывается на устройстве</span><span>⚡ быстрый предварительный скрининг</span></div></div></div>
  <section class="section"><div class="head"><div><small>ИНСТРУМЕНТЫ</small><h2>Что вам нужно?</h2></div><span class="free">БЕСПЛАТНО</span></div><div class="grid"><button class="card primary" id="cAnalyze"><div class="iconBox">⌑</div><span class="arrow">↗</span><b>Проверить документ</b><p>PDF, DOCX, TXT или фото. Риски, даты, суммы и условия.</p></button><button class="card" id="cCreate"><div class="iconBox">✎</div><span class="arrow">↗</span><b>Создать документ</b><p>Претензия, заявление, жалоба, требование.</p></button><button class="card" id="cAI"><div class="iconBox">◌</div><span class="arrow">↗</span><b>Спросить AI</b><p>Опишите ситуацию обычными словами.</p></button><button class="card special" id="cXray"><div class="iconBox">✦</div><span class="arrow">↗</span><b>Юридический рентген</b><p>Сделайте наглядный итог проверки и поделитесь им.</p></button></div></section>
  <section class="section"><div class="promo glass" id="promo"><small>ПЕРЕД ПОДПИСЬЮ</small><h3>Проверьте договор<br>до того, как подписать.</h3><p>Система найдёт места, которые стоит перечитать, уточнить или обсудить с юристом.</p><span class="promoBtn">Начать проверку →</span><div class="promoRing">⚖</div></div></section>
  <section class="section"><div class="head"><div><small>ПЛАТНЫЕ УСЛУГИ</small><h2>Когда нужен специалист</h2></div></div><div class="services"><article class="service"><div class="serviceTop"><div class="serviceIcon">♛</div><span class="tag">PRO</span></div><b>Проверка юристом</b><p>Ручной разбор документа и комментарии по ключевым пунктам.</p><button data-paid>Связаться →</button></article><article class="service"><div class="serviceTop"><div class="serviceIcon">✎</div><span class="tag">PRO</span></div><b>Подготовка документа</b><p>Индивидуальный текст под вашу ситуацию.</p><button data-paid>Заказать →</button></article><article class="service"><div class="serviceTop"><div class="serviceIcon">⚡</div><span class="tag">PRO</span></div><b>Срочная консультация</b><p>Когда вопрос нельзя откладывать.</p><button data-paid>Написать →</button></article></div></section>
  <section class="section"><div class="stats glass"><div><strong id="statChecks">0</strong><span>проверок</span></div><div><strong id="statDocs">0</strong><span>документов</span></div><div><strong id="statTests">0</strong><span>тестов</span></div></div></section><footer class="footer"><button data-paid style="background:none;color:#68d1ff;font-weight:900">Платные услуги в Telegram →</button><div>Право. Технологии. Твоя защита.</div><b>Made by kojenkov</b></footer></div>`;
    document.getElementById('hAnalyze').onclick=openAnalyze;document.getElementById('hAI').onclick=openAI;document.getElementById('cAnalyze').onclick=openAnalyze;document.getElementById('cCreate').onclick=openCreate;document.getElementById('cAI').onclick=openAI;document.getElementById('cXray').onclick=()=>openXray(state.report,state.name);document.getElementById('promo').onclick=openAnalyze;updateStats()
  }

  async function script(src){return new Promise((resolve,reject)=>{if(document.querySelector('script[src="'+src+'"]'))return resolve();const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>reject(new Error('Не удалось загрузить модуль распознавания'));document.head.appendChild(s)})}
  async function extract(file,status){if(file.size>MAX)throw new Error('Файл больше 10 МБ.');const ext=file.name.toLowerCase().split('.').pop();if(ext==='txt')return file.text();if(ext==='docx'){await script('https://cdnjs.cloudflare.com/ajax/libs/mammoth/1.8.0/mammoth.browser.min.js');const r=await window.mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()});return r.value||''}if(ext==='pdf'){if(!window.pdfjsLib)await script('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js');window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';const pdf=await window.pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;let out='';const n=Math.min(pdf.numPages,30);for(let i=1;i<=n;i++){status.textContent='Читаем страницу '+i+' из '+n+'…';const p=await pdf.getPage(i);const c=await p.getTextContent();out+=c.items.map(x=>x.str).join(' ')+'\n'}return out}if(['jpg','jpeg','png','webp'].includes(ext)){await script('https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js');const r=await window.Tesseract.recognize(file,'rus+eng',{logger:m=>{if(m.progress)status.textContent='Распознаём фото: '+Math.round(m.progress*100)+'%'}});return r.data.text||''}throw new Error('Поддерживаются PDF, DOCX, TXT, JPG, PNG и WEBP.')}

  function analyze(text){const t=text.replace(/\s+/g,' ').trim();const rs=[['Одностороннее изменение условий','Упоминания о возможности одной стороны менять цену, срок или иные условия.','Проверьте порядок согласования изменений.','Зафиксировать изменение только по письменному соглашению.','односторон|вправе.*изменить|может.*изменять',3],['Штрафы и неустойки','Есть санкции за нарушение обязательств.','Сверьте размер, условия начисления и предел ответственности.','Сопоставить санкции обеих сторон и верхний предел.','штраф|неустойк|пеня|пеню',2],['Автопродление','Есть признаки автоматического продления.','Проверьте срок уведомления и способ отказа.','Зафиксировать понятный срок и способ уведомления.','автоматическ.*продл|пролонгац',2],['Предоплата / аванс','Упомянут аванс, предоплата или задаток.','Проверьте основания удержания и возврата.','Отдельно зафиксировать условия возврата суммы.','предоплат|аванс|задаток',2],['Расторжение / отказ','Есть условия прекращения договора или отказа.','Сверьте основания, сроки уведомления и последствия.','Добавить ясный порядок и сроки уведомления.','расторжен|отказ.*от',2],['Ответственность','Есть раздел об ответственности сторон.','Проверьте баланс рисков и ограничения ответственности.','Сопоставить последствия одинаковых нарушений.','ответственност',1],['Порядок споров','Есть суд, подсудность или претензионный порядок.','Проверьте, куда и в какой срок нужно обращаться.','Уточнить юрисдикцию и обязательный досудебный порядок.','подсудн|арбитраж|суд|претензионн',1],['Персональные данные','Есть положения о персональных данных.','Проверьте цели обработки и состав данных.','Ограничить перечень и цель обработки.','персональн.*данн|152[- ]?фз',1],['Срок оплаты','Есть условия о расчётах и оплате.','Проверьте событие или дату, от которой считается срок.','Зафиксировать конкретный срок или событие.','срок.*оплат|оплат.*срок',1]];let issues=[];for(const r of rs)if(new RegExp(r[4],'iu').test(t))issues.push({title:r[0],note:r[1],why:r[2],fix:r[3],weight:r[5]});const dates=t.match(/\b\d{1,2}[./]\d{1,2}[./]\d{2,4}\b/g)||[];const money=t.match(/\b\d[\d\s]*(?:[.,]\d{1,2})?\s?(?:₽|руб(?:\.|лей)?)\b/giu)||[];const score=Math.min(100,34+issues.reduce((a,x)=>a+x.weight*7,0)+(dates.length?5:0)+(money.length?5:0));return{score,level:score>=72?'Внимание требуется':score>=55?'Есть что проверить':'Базовая проверка',issues:issues.slice(0,8),dates:dates.slice(0,10),money:money.slice(0,10),chars:t.length,type:detectType(t)}}
  function detectType(t){if(/аренд|найм жилья/.test(t))return'Договор аренды';if(/купли-продаж|продавец|покупател/.test(t))return'Купля-продажа';if(/трудов|работодател|зарплат/.test(t))return'Трудовой документ';if(/услуг|исполнитель|заказчик/.test(t))return'Оказание услуг';if(/кредит|займ|заём/.test(t))return'Кредит / займ';return'Документ'}
  function report(report,name){state.report=report;state.name=name;open('<h3 class="sheetTitle">Результат анализа</h3><p class="sheetSub">'+esc(name)+' · '+esc(report.type)+'</p><div class="stack"><div class="reportHead"><div class="score"><strong>'+report.score+'</strong></div><div><b>'+esc(report.level)+'</b><p>'+report.issues.length+' пунктов для внимания · '+report.chars.toLocaleString('ru-RU')+' символов</p></div></div>'+report.issues.map(x=>'<div class="issue"><div class="issueTop"><i class="issueDot"></i><div><strong>'+esc(x.title)+'</strong><p>'+esc(x.note)+'</p><div class="fix"><b>Почему важно:</b> '+esc(x.why)+'<br><b>Что проверить:</b> '+esc(x.fix)+'</div></div></div></div>').join('')+((report.dates.length||report.money.length)?'<div class="issue"><strong>Извлечённые данные</strong><p>'+ (report.dates.length?'Даты: '+esc(report.dates.join(', '))+'<br>':'') +(report.money.length?'Суммы: '+esc(report.money.join(', ')):'')+'</p></div>':'')+'<button class="wide" id="xrayReport">✦ Юридический рентген</button><button class="secondaryBtn" id="askDoc">Задать вопрос по документу</button><button class="secondaryBtn" id="payDoc">Проверить у юриста</button><div class="notice">Это автоматический предварительный скрининг. Он помогает ориентироваться в тексте, но не является юридическим заключением.</div></div>');document.getElementById('xrayReport').onclick=()=>openXray(report,name);document.getElementById('askDoc').onclick=()=>openDocAI(name,report);document.getElementById('payDoc').onclick=paid}

  function openAnalyze(){open('<h3 class="sheetTitle">Проверить документ</h3><p class="sheetSub">Можно загрузить несколько связанных файлов — основной договор, приложение и дополнение. Обработка выполняется локально в браузере.</p><div class="stack"><div class="upload"><div class="uploadIcon">⇧</div><b id="fileLabel">Выберите документы</b><small>PDF · DOCX · TXT · JPG · PNG · WEBP · до 10 МБ каждый</small><input id="fileInput" type="file" multiple accept=".pdf,.docx,.txt,.jpg,.jpeg,.png,.webp" hidden><button class="pick" id="pick">Выбрать файлы</button></div><textarea id="paste" class="field" placeholder="Или вставьте текст документа…"></textarea><button id="run" class="wide">Начать анализ</button><div id="status" class="status"></div></div>');const input=document.getElementById('fileInput'),label=document.getElementById('fileLabel'),status=document.getElementById('status');document.getElementById('pick').onclick=()=>input.click();input.onchange=e=>{state.files=[...e.target.files];label.textContent=state.files.length?('Выбрано файлов: '+state.files.length):'Выберите документы'};document.getElementById('run').onclick=async()=>{status.textContent='Готовим анализ…';try{let all=document.getElementById('paste').value.trim();let names=[];for(const f of state.files){status.textContent='Читаем '+f.name+'…';all+='\n'+await extract(f,status);names.push(f.name)}if(!all.trim()||all.trim().length<20)throw new Error('Нужно загрузить файл или вставить больше текста.');const r=analyze(all);state.stats.checks++;save();addHistory({type:'check',name:names.length?names.join(', '):'Вставленный текст',score:r.score,issues:r.issues.length});report(r,names.length?names.join(' + '):'Вставленный текст')}catch(e){status.textContent=e.message||'Не удалось обработать документ.'}}}

  function openCreate(){open('<h3 class="sheetTitle">Создать документ</h3><p class="sheetSub">Выберите задачу. Дальше приложение проведёт короткий диалог и соберёт только необходимые сведения.</p><div class="stack"><div class="choiceGrid">'+[['Претензия продавцу','Возврат денег и потребительские вопросы','consumer'],['Работодатель','Заявление, запрос, трудовой спор','work'],['Жалоба / обращение','Госорган, УК, организация','complaint'],['Требование по договору','Сроки, оплата, нарушение условий','claim'],['Соглашение / уведомление','Изменение или прекращение','notice'],['Другое','Опишите ситуацию AI','other']].map(x=>'<button class="choice" data-create="'+x[2]+'"><b>'+x[0]+'</b><span>'+x[1]+'</span></button>').join('')+'</div></div>');document.querySelectorAll('[data-create]').forEach(b=>b.onclick=()=>createForm(b.dataset.create))}
  const docTypes={consumer:'Претензия продавцу',work:'Заявление работодателю',complaint:'Жалоба / обращение',claim:'Требование по договору',notice:'Уведомление',other:'Юридический документ'};
  function createForm(type){open('<h3 class="sheetTitle">'+docTypes[type]+'</h3><p class="sheetSub">Шаг 1 из 2 · заполняйте как получается — формулировки потом можно отредактировать.</p><div class="stack"><input id="who" class="field smallInput" placeholder="Кому адресовать документ?"><textarea id="situation" class="field" placeholder="Что произошло? Укажите даты, суммы, документы и чего вы хотите добиться."></textarea><button class="wide" id="build">Собрать проект</button></div>');document.getElementById('build').onclick=()=>{const who=document.getElementById('who').value.trim(),s=document.getElementById('situation').value.trim();if(!who||s.length<15)return toast('Укажите адресата и опишите ситуацию');buildDoc(type,who,s)}}
  function buildDoc(type,who,s){const today=new Date().toLocaleDateString('ru-RU');const text='Кому: '+who+'\n\n'+docTypes[type]+'\n\nУважаемые господа!\n\nНастоящим сообщаю следующее:\n\n'+s+'\n\nНа основании изложенного прошу рассмотреть настоящее обращение и предоставить письменный ответ в установленный срок. При необходимости готов предоставить дополнительные документы.\n\nДата: '+today+'\nПодпись: ____________________';state.stats.docs++;addHistory({type:'document',name:docTypes[type]});open('<h3 class="sheetTitle">Проект готов</h3><p class="sheetSub">Документ можно отредактировать и скачать. Это черновик, перед отправкой проверьте факты.</p><div class="stack"><div class="doc" id="docPreview">'+esc(text).replace(/\n/g,'<br>')+'</div><button class="wide" id="downTxt">Скачать TXT</button><button class="secondaryBtn" id="editDoc">Редактировать</button><button class="secondaryBtn" id="payGen">Доработать с юристом</button></div>');document.getElementById('downTxt').onclick=()=>download(text,docTypes[type]+'.txt','text/plain;charset=utf-8');document.getElementById('editDoc').onclick=()=>editDoc(type,text);document.getElementById('payGen').onclick=paid}
  function editDoc(type,text){open('<h3 class="sheetTitle">Редактор документа</h3><p class="sheetSub">Измените формулировки и сохраните итоговый текст.</p><div class="stack"><textarea id="editor" class="field" style="min-height:280px">'+esc(text)+'</textarea><button class="wide" id="saveEdit">Сохранить</button></div>');document.getElementById('saveEdit').onclick=()=>{const v=document.getElementById('editor').value.trim();if(!v)return toast('Текст пуст');buildDoc(type,'',v)}}
  function download(data,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},800);toast('Файл подготовлен')}

  function openAI(){open('<h3 class="sheetTitle">AI-консультант</h3><p class="sheetSub">Вопросы, контекст и документы — в одном диалоге. Настоящий внешний AI подключим через защищённый backend, когда настроим ключ модели.</p><div class="stack"><div id="chat" class="chat"><div class="bubble ai">Здравствуйте. Опишите ситуацию обычными словами. Я помогу разложить её на факты, документы, сроки и возможные шаги.</div></div><div class="chatRow"><textarea id="chatInput" class="chatInput" placeholder="Напишите вопрос…"></textarea><button id="send" class="send">➤</button></div><div class="notice">Сейчас активен локальный помощник без передачи текста на внешний AI-сервис. Это сделано специально до подключения защищённого backend.</div></div>');const chat=document.getElementById('chat'),input=document.getElementById('chatInput');const send=()=>{const q=input.value.trim();if(!q)return;chat.insertAdjacentHTML('beforeend','<div class="bubble me">'+esc(q)+'</div>');input.value='';chat.insertAdjacentHTML('beforeend','<div class="bubble ai">'+esc(localAnswer(q))+'</div>');chat.scrollTop=chat.scrollHeight};document.getElementById('send').onclick=send;input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}})}
  function openDocAI(name,report){open('<h3 class="sheetTitle">Вопрос по документу</h3><p class="sheetSub">Контекст: '+esc(name)+'. Индекс внимания: '+report.score+'/100.</p><div class="stack"><div class="chat" id="docchat"><div class="bubble ai">Я вижу '+report.issues.length+' пункта(ов) для внимания. Спросите, например: «какие пункты проверить в первую очередь?»</div></div><div class="chatRow"><textarea id="docq" class="chatInput" placeholder="Вопрос по этому документу…"></textarea><button id="docs" class="send">➤</button></div></div>');const c=document.getElementById('docchat'),q=document.getElementById('docq');const go=()=>{const s=q.value.trim();if(!s)return;c.insertAdjacentHTML('beforeend','<div class="bubble me">'+esc(s)+'</div><div class="bubble ai">'+esc(reportAnswer(s,report))+'</div>');q.value='';c.scrollTop=c.scrollHeight};document.getElementById('docs').onclick=go;q.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();go()}})}
  function localAnswer(q){const t=q.toLowerCase();if(/вернут|деньг|магазин|товар/.test(t))return'Сохраните чек, подтверждение оплаты, переписку и сам документ. Затем зафиксируйте дату покупки, проблему и отказ продавца — по этим данным можно подготовить претензию.';if(/увол|работ|зарплат/.test(t))return'Сохраните документы от работодателя, даты, переписку и расчёт. Не подписывайте непонятный документ до того, как разберётесь в его содержании.';if(/аренд|квартир|залог/.test(t))return'Проверьте договор: срок, залог, расторжение, штрафы и порядок уведомления. Можете загрузить договор для предварительного скрининга.';if(/пристав|штраф|долг|взыск/.test(t))return'Определите отправителя, название документа, дату и указанный срок. Важно смотреть сам текст документа, а не только тему сообщения.';return'Разложите ситуацию на четыре части: что произошло, когда, какие документы у вас есть и какого результата вы хотите. После этого выберите анализ документа или создание нужного обращения.'}
  function reportAnswer(q,r){const t=q.toLowerCase();if(/риск|опас|важн/.test(t))return'В первую очередь посмотрите пункты с наибольшим весом. Сейчас приложение отметило: '+r.issues.slice(0,4).map(x=>x.title).join(', ')+'. Это предварительный скрининг — окончательная оценка зависит от текста и обстоятельств.';if(/срок/.test(t))return r.dates.length?'В тексте найдены даты: '+r.dates.join(', ')+'. Их нужно сопоставить с условиями договора и фактическими обстоятельствами.':'В тексте не удалось уверенно извлечь даты. Проверьте сроки вручную.';if(/деньг|сумм|цен/.test(t))return r.money.length?'Найдены суммы: '+r.money.join(', ')+'. Проверьте, к какому именно обязательству каждая сумма относится.':'Суммы не были уверенно распознаны из текста.';return'Я могу помочь разобрать отмеченные пункты, но сейчас локальный режим работает без внешней юридической базы. Для настоящего контекстного ответа по документу подключим защищённый AI backend.'}

  function openXray(report,name){if(!report){open('<h3 class="sheetTitle">Юридический рентген</h3><p class="sheetSub">Сначала загрузите документ и запустите анализ.</p><div class="stack"><button class="wide" id="xr0">Проверить документ</button></div>');document.getElementById('xr0').onclick=openAnalyze;return}const high=report.issues.filter(x=>x.weight>=2).length,medium=report.issues.length-high;const shareText='⚖️ Юридический рентген\n'+name+'\nИндекс внимания: '+report.score+'/100\nПунктов для внимания: '+report.issues.length+'\n\nЮрист объясняет | AI';open('<h3 class="sheetTitle">Юридический рентген</h3><p class="sheetSub">Наглядный итог проверки документа.</p><div class="stack"><div class="reportHead"><div class="score"><strong>'+report.score+'</strong></div><div><b>'+high+' серьёзных</b><p>'+medium+' дополнительных пунктов для внимания</p></div></div><div class="issue"><strong>'+esc(name)+'</strong><p>'+esc(report.type)+' · '+report.chars.toLocaleString('ru-RU')+' символов</p></div><button class="wide" id="share">Поделиться результатом</button><button class="secondaryBtn" id="goAI">Спросить AI о документе</button><div class="notice">Карточка показывает результат автоматического скрининга, а не степень законности документа.</div></div>');document.getElementById('share').onclick=()=>{const u='https://t.me/share/url?url='+encodeURIComponent('https://kojenkovd.github.io/yurist-explains-ai/')+'&text='+encodeURIComponent(shareText);if(tg?.openTelegramLink)tg.openTelegramLink(u);else navigator.clipboard?.writeText(shareText).then(()=>toast('Результат скопирован'))};document.getElementById('goAI').onclick=()=>openDocAI(name,report)}

  function renderDocuments(){const rows=state.history.slice().reverse();view.innerHTML='<div class="section" style="padding-top:28px"><div class="head"><div><small>МОИ ДОКУМЕНТЫ</small><h2>История</h2></div><span class="free">ЛОКАЛЬНО</span></div><div class="stack">'+(rows.length?rows.map(x=>'<div class="issue"><strong>'+esc(x.name||'Без названия')+'</strong><p>'+esc(x.type==='check'?('Проверка · индекс '+(x.score??'—')+'/100'):('Создан документ'))+' · '+new Date(x.at).toLocaleString('ru-RU')+'</p></div>').join(''):'<div class="empty">История пока пуста.<br><br>Начните с проверки документа или создания первого обращения.</div>')+'</div></div><div class="section"><button class="wide" id="newCheck">+ Новая проверка</button></div><footer class="footer"><b>Made by kojenkov</b></footer>';document.getElementById('newCheck').onclick=openAnalyze}
  function renderProfile(){view.innerHTML='<div class="section" style="padding-top:28px"><div class="head"><div><small>ПРОФИЛЬ</small><h2>Ваш кабинет</h2></div></div><div class="reportHead"><div class="score"><strong>Д</strong></div><div><b>Юрист объясняет | AI</b><p>История и статистика хранятся локально на устройстве.</p></div></div></div><div class="section"><div class="stats glass"><div><strong>'+state.stats.checks+'</strong><span>проверок</span></div><div><strong>'+state.stats.docs+'</strong><span>документов</span></div><div><strong>'+state.stats.tests+'</strong><span>тестов</span></div></div></div><div class="section"><div class="stack"><button class="secondaryBtn" id="historyBtn">Открыть историю</button><button class="secondaryBtn" id="paidProfile">Платные услуги</button><button class="secondaryBtn" id="clear">Очистить локальную историю</button></div></div><footer class="footer"><div>Право. Технологии. Твоя защита.</div><b>Made by kojenkov</b></footer>';document.getElementById('historyBtn').onclick=()=>nav('documents');document.getElementById('paidProfile').onclick=paid;document.getElementById('clear').onclick=()=>{localStorage.removeItem('jeai_history');state.history=[];state.stats={checks:0,docs:0,tests:0};save();toast('История очищена');renderProfile()}}

  renderHome();
})();
