(() => {
  const cfg = window.JEAI_CONFIG || {paidTelegram:'kojenkovv',aiEndpoint:'',maxFileMb:10};
  const tg = window.Telegram?.WebApp;
  if (tg) { tg.ready(); tg.expand(); try { tg.setHeaderColor('#061227'); tg.setBackgroundColor('#020810'); } catch(_){} }
  const $ = s => document.querySelector(s);
  const $$ = s => [...document.querySelectorAll(s)];
  const esc = s => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const modal=$('#modal'), body=$('#modalBody'), toastEl=$('#toast');
  const state={view:'home',file:null,text:'',report:null,history:load('jeai_history',[]),stats:load('jeai_stats',{checks:0,docs:0,ai:0,tests:0})};
  let toastTimer;
  function load(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch(_){return d}}
  function save(){localStorage.setItem('jeai_history',JSON.stringify(state.history.slice(-50)));localStorage.setItem('jeai_stats',JSON.stringify(state.stats));}
  function toast(m){toastEl.textContent=m;toastEl.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toastEl.classList.remove('show'),2300)}
  function paid(){const u=(cfg.paidTelegram||'kojenkovv').replace(/^@/,'');if(tg?.openTelegramLink)tg.openTelegramLink('https://t.me/'+u);else window.open('https://t.me/'+u,'_blank','noopener')}
  function open(html){body.innerHTML=html;modal.classList.add('open');modal.setAttribute('aria-hidden','false')}
  function close(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');body.innerHTML='';state.file=null}
  function addHist(item){state.history.push({at:new Date().toLocaleString('ru-RU'),...item});save()}
  function nav(v){state.view=v;$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));render()}

  const icons={home:'⌂',analyze:'▣',create:'＋',ai:'◌',xray:'✦',history:'◷'};
  function render(){const c=$('#content'); if(state.view==='home')renderHome(); else if(state.view==='analyze')openAnalyze(); else if(state.view==='create')openCreate(); else if(state.view==='ai')openAI(); else if(state.view==='xray')openXray(state.report); else if(state.view==='history')renderHistory(); window.scrollTo({top:0,behavior:'smooth'})}

  function renderHome(){
    $('#content').innerHTML=`<div class="page">
      <section class="hero"><div class="hero-copy"><div class="eyebrow"><i></i> РОССИЯ · ONLINE</div><h1>Юрист объясняет.<br><span>Просто. Чётко. По делу.</span></h1><p class="hero-lead">Проверяйте документы, создавайте юридические тексты и задавайте вопросы AI — в одном месте, внутри Telegram.</p><div class="hero-actions"><button class="btn btn-blue" id="heroAnalyze">✦ Проверить документ</button><button class="btn btn-gold" id="heroCreate">＋ Создать документ</button><button class="btn btn-dark" id="heroAI">◌ Спросить AI</button></div><div class="trust"><span>⌾ файл остаётся на устройстве</span><span>⚡ предварительный скрининг</span><span>⚖ помощь юриста: @kojenkovv</span></div></div><div class="hero-art"><img src="./background.jpg" alt="Фемида"><div class="hero-badge"><b>Made by kojenkov</b><br>Право · Технологии · Твоя защита</div></div></section>
      <div class="stat-strip"><div class="stat"><div class="sicon">▣</div><div><b>${state.stats.checks||0}</b><span>проверок на устройстве</span></div></div><div class="stat"><div class="sicon">＋</div><div><b>${state.stats.docs||0}</b><span>создано документов</span></div></div><div class="stat"><div class="sicon">◌</div><div><b>${state.stats.ai||0}</b><span>вопросов AI</span></div></div></div>
      <section><div class="section-title"><div><small>БЫСТРЫЙ СТАРТ</small><h2>Выберите задачу</h2></div><span class="gold-chip">ВСЕ ФУНКЦИИ</span></div><div class="quick-grid"><button class="quick primary" id="quickAnalyze"><div class="qicon">▣</div><span class="qgo">↗</span><b>Проверить документ</b><p>PDF, DOCX, TXT, JPG, PNG, WEBP. Риски, даты, суммы и условия.</p></button><button class="quick" id="quickCreate"><div class="qicon">＋</div><span class="qgo">↗</span><b>Создать документ</b><p>Претензия, заявление, жалоба, требование и другие тексты.</p></button><button class="quick" id="quickAI"><div class="qicon">◌</div><span class="qgo">↗</span><b>AI-ассистент</b><p>Опишите ситуацию или продолжите разговор после проверки документа.</p></button><button class="quick primary" id="quickXray"><div class="qicon">✦</div><span class="qgo">↗</span><b>Юридический рентген</b><p>Наглядный итог проверки и карточка для Telegram.</p></button></div></section>
      <section><div class="section-title"><div><small>РАБОТА</small><h2>Результаты и документы</h2></div><button class="panel-link" id="homeHistory">Все →</button></div><div class="lower-grid"><div class="panel"><div class="panel-top"><h3>Последние проверки</h3><button class="panel-link" id="checksAll">Все →</button></div>${recentChecks()}</div><div class="panel"><div class="panel-top"><h3>Статистика</h3><span class="gold-chip">LIVE</span></div><div class="mini-chart"><div class="donut"><span>89%</span></div></div><div class="chart-legend"><div><span>Проверено</span><b>${state.stats.checks||0}</b></div><div><span>Создано</span><b>${state.stats.docs||0}</b></div><div><span>AI</span><b>${state.stats.ai||0}</b></div></div></div><div class="panel xray"><div class="panel-top"><h3>Юридический рентген</h3><span class="gold-chip">PRO</span></div><div class="orb">✦</div><p>Глубокий разбор документа, рисков и условий с понятными объяснениями.</p><button class="btn btn-blue" id="xrayStart">Запустить →</button></div></div></section>
      <footer style="padding:24px 0 0;color:#637e9f;text-align:center;font-size:9px">Платные услуги и ручная проверка: <a href="https://t.me/kojenkovv" target="_blank" style="color:#67d2ff;font-weight:900">@kojenkovv</a> · Made by <b style="color:#9fc9ef">kojenkov</b></footer>
    </div>`;
    $('#heroAnalyze').onclick=openAnalyze;$('#heroCreate').onclick=openCreate;$('#heroAI').onclick=openAI;$('#quickAnalyze').onclick=openAnalyze;$('#quickCreate').onclick=openCreate;$('#quickAI').onclick=openAI;$('#quickXray').onclick=()=>openXray(state.report);$('#homeHistory').onclick=()=>nav('history');$('#checksAll').onclick=()=>nav('history');$('#xrayStart').onclick=()=>openXray(state.report);
    bindPaid(); updateQuota();
  }
  function recentChecks(){const rows=state.history.filter(x=>x.type==='check').slice(-5).reverse(); if(!rows.length)return '<div class="doc-row"><div class="doc-ico">⌑</div><div class="doc-main"><b>Пока нет проверок</b><span>Загрузите первый документ</span></div></div>';return rows.map(r=>`<div class="doc-row"><div class="doc-ico">▤</div><div class="doc-main"><b>${esc(r.name)}</b><span>${esc(r.at)}</span></div><span class="tag ${r.score>=70?'hot':r.score>=55?'mid':'ok'}">${r.score>=70?'ВНИМАНИЕ':r.score>=55?'УТОЧНИТЬ':'СПОКОЙНО'}</span></div>`).join('')}
  function bindPaid(){$$('[data-paid]').forEach(b=>b.onclick=e=>{e.preventDefault();paid()});$('#topPremium')?.addEventListener('click',paid)}
  function updateQuota(){const q=Math.min(3,(state.stats.checks||0));const n=3-q;const qc=$('#quotaCount');const qb=$('#quotaBar');if(qc)qc.textContent=n; if(qb)qb.style.width=(n/3*100)+'%'}

  async function loadScript(src){return new Promise((resolve,reject)=>{if(document.querySelector('script[src="'+src+'"]'))return resolve();const s=document.createElement('script');s.src=src;s.async=true;s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
  async function extract(file,status){if(file.size>10*1024*1024)throw new Error('Файл больше 10 МБ.');const ext=file.name.toLowerCase().split('.').pop();if(ext==='txt')return await file.text();if(ext==='docx'){await loadScript('https://cdnjs.cloudflare.com/ajax/libs/mammoth/1.8.0/mammoth.browser.min.js');const r=await window.mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()});return r.value||''}if(ext==='pdf'){await loadScript('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js');window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';const pdf=await window.pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;let out='';const total=Math.min(pdf.numPages,30);for(let i=1;i<=total;i++){status.textContent='Читаем страницу '+i+' из '+total+'…';const p=await pdf.getPage(i);const c=await p.getTextContent();out+=c.items.map(x=>x.str).join(' ')+'\n'}return out}if(['jpg','jpeg','png','webp'].includes(ext)){await loadScript('https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js');const r=await window.Tesseract.recognize(file,'rus+eng',{logger:m=>{if(m.progress)status.textContent='Распознаём фото: '+Math.round(m.progress*100)+'%'}});return r.data.text||''}throw new Error('Поддерживаются PDF, DOCX, TXT, JPG, PNG и WEBP.');}

  function analyze(text){const t=text.replace(/\s+/g,' ').trim();const rules=[
    ['Одностороннее изменение условий','В тексте есть условие, при котором одна сторона может менять цену, срок или другие параметры.','Проверьте, какие изменения допускаются и нужен ли отдельный письменный документ.','Изменения — только по письменному соглашению сторон.','односторон|вправе.*изменить|может.*изменять',3],
    ['Штрафы и неустойки','Найдены санкции за нарушение обязательств.','Сверьте размер, порядок расчёта, предел суммы и симметрию ответственности.','Уточните размер и предел начисления неустойки.','штраф|неустойк|пеня|пеню',2],
    ['Автопродление','Похоже, договор может продлеваться автоматически.','Важен срок и способ уведомления об отказе от продления.','Зафиксируйте понятный срок и способ уведомления.','автоматическ.*продл|пролонгац',2],
    ['Предоплата / аванс','Упомянуты аванс, предоплата или задаток.','Нужно проверить основания возврата или удержания суммы.','Порядок возврата лучше прописать отдельно.','предоплат|аванс|задаток',2],
    ['Расторжение договора','Есть положения о расторжении или одностороннем отказе.','Сверьте основания, сроки уведомления и финансовые последствия.','Сделайте основания и срок уведомления однозначными.','расторжен|отказ.*от',2],
    ['Ответственность сторон','В документе есть условия об ответственности.','Проверьте, одинаково ли распределены риски между сторонами.','Сверьте санкции и ограничения ответственности обеих сторон.','ответственност',1],
    ['Порядок споров','Есть условия о суде, подсудности или претензионном порядке.','Нужно понимать, куда и в какой последовательности обращаться.','Проверьте юрисдикцию и обязательный досудебный порядок.','подсудн|арбитраж|суд|претензионн',1],
    ['Персональные данные','Есть положение о персональных данных.','Проверьте состав данных, цели, передачу и сроки хранения.','Согласуйте только необходимые данные и понятную цель обработки.','персональн.*данн|152[- ]?фз',1],
    ['Срок оплаты','Есть условия о сроке оплаты.','Проверьте, от какого события начинает течь срок и что считается просрочкой.','Лучше привязать срок к конкретной дате или событию.','срок.*оплат|оплат.*срок',1]
  ];const issues=[];for(const r of rules)if(new RegExp(r[4],'iu').test(t))issues.push({title:r[0],note:r[1],why:r[2],fix:r[3],weight:r[5]});const dates=t.match(/\b\d{1,2}[./]\d{1,2}[./]\d{2,4}\b/g)||[];const money=t.match(/\b\d[\d\s]*(?:[.,]\d{1,2})?\s?(?:₽|руб(?:\.|лей)?)\b/giu)||[];const score=Math.min(100,32+issues.reduce((a,x)=>a+x.weight*8,0)+(dates.length?5:0)+(money.length?5:0));return{score,issues,dates:dates.slice(0,10),money:money.slice(0,10),chars:t.length,type:detectType(t)}}
  function detectType(t){if(/аренд|найм.*жиль/i.test(t))return'Договор аренды';if(/купли-продаж|продавец|покупател/i.test(t))return'Купля-продажа';if(/трудов|работодател|работник|зарплат/i.test(t))return'Трудовой документ';if(/оказани[ея] услуг|исполнитель|заказчик/i.test(t))return'Оказание услуг';if(/кредит|займ|заём/i.test(t))return'Кредит / займ';return'Документ'}

  function openAnalyze(){open(`<h3 class="m-title">Проверка документа</h3><p class="m-sub">Загрузите один или несколько файлов. Текст извлекается на этом устройстве, после чего выполняется предварительный юридический скрининг.</p><div class="stack"><div class="upload"><div class="upload-icon">⇧</div><b id="fileLabel">Выберите документы</b><small>PDF · DOCX · TXT · JPG · PNG · WEBP · до 10 МБ каждый</small><input id="fileInput" type="file" hidden multiple accept=".pdf,.docx,.txt,.jpg,.jpeg,.png,.webp"><button class="pick" id="pickFile">Выбрать файлы</button></div><textarea id="pasteText" class="field textarea" placeholder="Или вставьте текст документа…"></textarea><button class="wide" id="runAnalysis">Начать анализ</button><div id="status" class="legal-note"></div></div>`);const input=$('#fileInput'),label=$('#fileLabel'),status=$('#status');input.onchange=e=>{const fs=[...e.target.files];state.files=fs;label.textContent=fs.length?`Выбрано файлов: ${fs.length}`:'Выберите документы'};$('#pickFile').onclick=()=>input.click();$('#runAnalysis').onclick=async()=>{status.textContent='Подготовка…';try{let text=$('#pasteText').value.trim();let names=[];if(state.files?.length){for(const f of state.files){names.push(f.name);text+='\n\n'+(await extract(f,status))}}if(text.length<30)throw new Error('Нужно больше текста для анализа.');const r=analyze(text);state.report=r;state.text=text;state.fileName=names.join(', ')||'Вставленный текст';state.stats.checks++;addHist({type:'check',name:state.fileName,score:r.score,issues:r.issues.length});openReport(r,state.fileName)}catch(e){status.textContent=e.message||'Не удалось обработать документ.'}}}
  function openReport(r,name){const label=r.score>=70?'Требуется внимание':r.score>=55?'Есть пункты для проверки':'Базовая проверка';open(`<h3 class="m-title">Результат анализа</h3><p class="m-sub">${esc(name)} · ${esc(r.type)}</p><div class="report"><div class="report-hero"><div class="score"><strong>${r.score}</strong></div><div><b style="font-size:14px">${label}</b><p style="margin:5px 0 0;color:#9fb3ce;font-size:10px">Найдено пунктов для внимания: ${r.issues.length}</p></div></div>${r.issues.length?r.issues.map(x=>`<div class="risk"><div class="risk-head"><i class="risk-dot"></i><div><b>${esc(x.title)}</b><p>${esc(x.note)} ${esc(x.why)}</p><div class="fix"><b>Что проверить:</b> ${esc(x.fix)}</div></div></div></div>`).join(''):'<div class="risk"><b>Явных триггеров не найдено</b><p>Это не подтверждает юридическую корректность документа. Автоматический скрининг не заменяет правовую экспертизу.</p></div>'}${(r.dates.length||r.money.length)?`<div class="risk"><b>Найденные данные</b><p>${r.dates.length?'Даты: '+esc(r.dates.join(', '))+'<br>':''}${r.money.length?'Суммы: '+esc(r.money.join(', ')):''}</p></div>`:''}<button class="wide" id="reportXray">Сделать юридический рентген</button><button class="wide gold" id="reportPaid">Передать документ юристу</button><div class="legal-note">Сервис помогает ориентироваться в тексте. Итоговые юридические выводы зависят от обстоятельств дела и применимого права.</div></div>`);$('#reportXray').onclick=()=>openXray(r);$('#reportPaid').onclick=paid}

  function openCreate(){open(`<h3 class="m-title">Создать документ</h3><p class="m-sub">Выберите задачу. Затем приложение задаст минимальный набор вопросов и соберёт проект.</p><div class="choice-grid">${[['Претензия продавцу','Возврат денег, товар или услуга','consumer'],['Заявление работодателю','Трудовая ситуация','work'],['Жалоба / обращение','Госорган, УК, организация','complaint'],['Требование по договору','Обязательства контрагента','claim'],['Заявление в суд','Проект обращения','court'],['Другое','Описать задачу AI','other']].map(x=>`<button class="choice" data-create="${x[2]}"><b>${x[0]}</b><span>${x[1]}</span></button>`).join('')}</div>`);$$('[data-create]').forEach(b=>b.onclick=()=>createForm(b.dataset.create))}
  const typeNames={consumer:'Претензия продавцу',work:'Заявление работодателю',complaint:'Жалоба / обращение',claim:'Требование по договору',court:'Заявление в суд',other:'Юридический документ'};
  function createForm(t){open(`<h3 class="m-title">${typeNames[t]}</h3><p class="m-sub">Опишите ситуацию. Достаточно фактов, дат, сумм и того, чего вы хотите добиться.</p><div class="stack"><input id="to" class="field" placeholder="Кому документ? (магазин, работодатель, УК…)"/><textarea id="situation" class="field textarea" placeholder="Что произошло? Когда? Какая сумма? Что уже делали?"></textarea><button class="wide" id="buildDoc">Сформировать проект</button></div>`);$('#buildDoc').onclick=()=>{const to=$('#to').value.trim(),s=$('#situation').value.trim();if(!to||s.length<15){toast('Заполните адресата и опишите ситуацию');return}generateDoc(t,to,s)}}
  function generateDoc(t,to,s){const today=new Date().toLocaleDateString('ru-RU');const title=typeNames[t];const body=`${title.toUpperCase()}\n\nКому: ${to}\n\nУважаемые представители ${to}!\n\nОбстоятельства:\n${s}\n\nПрошу рассмотреть настоящее обращение и предоставить письменный ответ в установленный срок. При необходимости готов предоставить дополнительные документы.\n\nДата: ${today}\nПодпись: ____________________`;state.stats.docs++;addHist({type:'document',name:title});open(`<h3 class="m-title">Проект документа</h3><p class="m-sub">${esc(title)} · черновик для редактирования.</p><div class="stack"><textarea id="docEdit" class="field textarea" style="min-height:280px">${esc(body)}</textarea><button class="wide" id="downloadTxt">Скачать TXT</button><button class="wide gold" id="downloadDoc">Скачать для Word</button><button class="wide" id="docPaid">Нужна индивидуальная доработка</button><div class="legal-note">Перед отправкой проверьте даты, суммы, адресата и правовые основания.</div></div>`);$('#downloadTxt').onclick=()=>downloadFile(title+'.txt','text/plain;charset=utf-8',$('#docEdit').value);$('#downloadDoc').onclick=()=>downloadFile(title+'.doc','application/msword','<html><meta charset="utf-8"><body>'+esc($('#docEdit').value).replace(/\n/g,'<br>')+'</body></html>');$('#docPaid').onclick=paid}
  function downloadFile(name,type,data){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},700);toast('Файл подготовлен')}

  function openAI(){state.stats.ai++;save();open(`<h3 class="m-title">AI-ассистент</h3><p class="m-sub">Задавайте вопросы по ситуации. После анализа документа здесь можно продолжить разговор с его контекстом.</p><div class="stack"><div class="chat" id="chat"><div class="bubble ai">Здравствуйте. Расскажите, что произошло, или задайте вопрос по документу.</div></div><div class="chat-row"><textarea class="chat-input field" id="chatInput" placeholder="Напишите сообщение…"></textarea><button class="send" id="send">➤</button></div><div class="legal-note">В этой версии без подключённого endpoint используется локальный помощник. Настоящий AI будет подключён через защищённый backend, чтобы ключ не попадал в браузер.</div></div>`);const chat=$('#chat'),input=$('#chatInput');const send=async()=>{const q=input.value.trim();if(!q)return;chat.insertAdjacentHTML('beforeend',`<div class="bubble me">${esc(q)}</div>`);input.value='';const ans=await aiAnswer(q);chat.insertAdjacentHTML('beforeend',`<div class="bubble ai">${esc(ans)}</div>`);chat.scrollTop=chat.scrollHeight};$('#send').onclick=send;input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}}
  async function aiAnswer(q){if(cfg.aiEndpoint){try{const r=await fetch(cfg.aiEndpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({question:q,documentText:state.text||''})});if(r.ok){const d=await r.json();if(d.answer)return d.answer}}catch(_){}}const t=q.toLowerCase();if(/аренд|квартир|залог/.test(t))return'Проверьте договор аренды: срок, условия возврата залога, порядок расторжения и способ уведомления. Пришлите текст договора — я отмечу конкретные пункты.';if(/работ|увол|зарплат/.test(t))return'Зафиксируйте документы от работодателя, даты и переписку. Не подписывайте документы, смысл которых не успели проверить.';if(/деньг|магазин|товар|возврат/.test(t))return'Сохраните чек, подтверждение оплаты, переписку и дату обращения продавцу. Затем можно подготовить претензию с конкретным требованием.';if(/штраф|долг|пристав|взыск/.test(t))return'Посмотрите, кто направил документ, его дату, основание требования и указанный срок. Важен сам текст документа, а не только его название.';return state.report?`По вашему последнему документу автоматический скрининг отметил ${state.report.issues.length} пунктов для внимания. Можно открыть результат и посмотреть детали.`:'Разложите ситуацию на факты, даты, документы и желаемый результат. После этого выберите анализ документа или создание нужного обращения.'}

  function openXray(r){if(!r){open(`<h3 class="m-title">Юридический рентген</h3><p class="m-sub">Сначала загрузите документ и проведите проверку.</p><div class="stack"><button class="wide" id="xrAnalyze">Проверить документ</button></div>`);$('#xrAnalyze').onclick=openAnalyze;return}const severe=r.issues.filter(x=>x.weight>=2).length;const other=r.issues.length-severe;open(`<h3 class="m-title">Юридический рентген</h3><p class="m-sub">${esc(state.fileName||r.type)}</p><div class="stack"><div class="report-hero"><div class="score"><strong>${r.score}</strong></div><div><b>${severe} серьёзных пункта</b><p>${other} дополнительных</p></div></div><div class="risk"><b>Карточка результата готова</b><p>Её можно отправить другу или использовать как приглашение проверить свой документ.</p></div><button class="wide gold" id="share">Поделиться в Telegram</button><button class="wide" id="paidX">Передать документ юристу</button></div>`);$('#share').onclick=()=>{const text=`⚖️ Юридический рентген\n${state.fileName||r.type}\nИндекс внимания: ${r.score}/100\nПунктов для внимания: ${r.issues.length}\nЮрист объясняет | AI`;const url='https://t.me/share/url?url='+encodeURIComponent('https://kojenkovd.github.io/yurist-explains-ai/')+'&text='+encodeURIComponent(text);if(tg?.openTelegramLink)tg.openTelegramLink(url);else window.open(url,'_blank','noopener')};$('#paidX').onclick=paid}

  function renderHistory(){const rows=state.history.slice().reverse();$('#content').innerHTML=`<div class="page"><div class="section-title" style="margin-top:0"><div><small>ИСТОРИЯ</small><h2>Ваши проверки и документы</h2></div><span class="gold-chip">${rows.length} записей</span></div><div class="panel">${rows.length?rows.map(r=>`<div class="doc-row"><div class="doc-ico">${r.type==='check'?'▣':'＋'}</div><div class="doc-main"><b>${esc(r.name)}</b><span>${esc(r.at)}${r.score?` · индекс ${r.score}/100`:''}</span></div><span class="tag ${r.type==='check'?(r.score>=70?'hot':r.score>=55?'mid':'ok'):'ok'}">${r.type==='check'?'ПРОВЕРЕНО':'СОЗДАНО'}</span></div>`).join(''):'<div class="doc-row"><div class="doc-main"><b>История пуста</b><span>Сделайте первую проверку или создайте документ.</span></div></div>'}</div><div class="stack" style="max-width:420px;margin-top:12px"><button class="wide" id="historyAnalyze">Проверить новый документ</button><button class="wide gold" id="historyClear">Очистить историю</button></div></div>`;$('#historyAnalyze').onclick=openAnalyze;$('#historyClear').onclick=()=>{state.history=[];state.stats={checks:0,docs:0,ai:0,tests:0};save();toast('История очищена');renderHistory()}}

  $('#sideNav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)nav(b.dataset.view)});$('#mobileNav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)nav(b.dataset.view)});document.addEventListener('click',e=>{if(e.target.closest('[data-close]'))close();if(e.target.closest('[data-paid]')){e.preventDefault();paid()}});
  $('#search').addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();if(q.length>2){if(/документ|договор|провер/.test(q))toast('Откройте «Анализ документов»');else if(/претенз|жалоб|заявлен/.test(q))toast('Откройте «Создание документов»');else if(/юрист|консульт/.test(q))paid()}});
  renderHome();
})();
